-- Update LG Business Cloud Chatbot
UPDATE projects 
SET 
    process = '["Developed in a small team consisting of 1 frontend developer (myself) and 2 backend developers", "Designed to allow LG Business Cloud solution users to easily access necessary information", "Provides answers to solution-related questions, troubleshooting guides, and a button-type UI for frequently asked questions", "Implemented RAG (Retrieval Augmented Generation) based on internal documents to provide accurate answers", "Vectorized technical documentation and FAQ data to build a search infrastructure", "Implemented document search and summarization functions tailored to the user''s question intent"]',
    process_ko = '["프론트엔드 개발자 1명(본인), 백엔드 개발자 2명으로 구성된 소규모 팀으로 개발 진행", "LG Business Cloud 솔루션 사용자들이 필요한 정보를 쉽게 얻을 수 있도록 설계", "솔루션 관련 질문 답변, 문제 해결 가이드, 자주 묻는 질문 버튼형 UI 제공", "사내 문서 기반 RAG(Retrieval Augmented Generation) 구현으로 정확한 답변 제공", "기술문서 및 FAQ 데이터를 벡터화하여 검색 인프라 구축", "사용자 질문 의도에 맞는 문서 검색 및 요약 기능 구현"]',
    developed = '["Directly implemented chat message display and input components (minimized use of external libraries)", "Real-time message streaming processing using WebSocket", "Implemented connection maintenance and reconnection logic with the server", "Rendering branching processing according to message type (text, HTML, buttons, etc.)", "Integrated interface for button-type quick responses and natural language question processing", "Dynamic generation function for recommended question buttons by situation", "Implemented customized recommendation logic based on user login count and license holdings", "Applied responsive design for mobile environment support", "Designed API interface and defined data structure with backend developers", "Defined interface for RESTful API and WebSocket communication", "Improved communication efficiency with message packet optimization", "Responsible for deploying final build files to S3 static hosting", "Led monitoring, bug fixing, and performance improvement work after launch"]',
    developed_ko = '["채팅 메시지 표시 및 입력 컴포넌트 직접 구현 (외부 라이브러리 사용 최소화)", "WebSocket을 활용한 실시간 메시지 스트리밍 처리", "서버와의 연결 유지 및 재연결 로직 구현", "메시지 타입에 따른 렌더링 분기 처리 (텍스트, HTML, 버튼 등)", "버튼형 빠른 응답과 자연어 질문 처리를 위한 통합 인터페이스", "상황별 추천 질문 버튼 동적 생성 기능", "사용자 로그인 횟수 및 라이센스 보유 기반 맞춤형 추천 로직 구현", "모바일 환경 대응을 위한 반응형 디자인 적용", "백엔드 개발자들과 API 인터페이스 설계 및 데이터 구조 정의", "RESTful API와 WebSocket 통신을 위한 인터페이스 정의", "메시지 패킷 최적화로 통신 효율성 향상", "최종 빌드 파일 S3 정적 호스팅으로 배포 담당", "출시 후 모니터링 및 버그 수정, 성능 개선 작업 주도"]'
WHERE slug = 'lg-business-cloud-chatbot';

-- Update In-house LED Outsourcing Team System
UPDATE projects 
SET 
    process = '["I was solely responsible for the entire system construction, including frontend, backend, data processing, visualization, and ETL", "Constructed a customized system for data management, status identification, and analysis to achieve project goals", "Utilized GCP BigQuery, MariaDB, Elasticsearch, Kibana, React, FastAPI, Pandas, Numpy, Airflow"]',
    process_ko = '["프론트엔드, 백엔드, 데이터 처리, 시각화, ETL 등 시스템 구축 전반을 본인 1인이 담당", "프로젝트 목표 달성을 위한 데이터 관리, 현황 파악, 분석 맞춤형 시스템 구축", "GCP BigQuery, MariaDB, Elasticsearch, Kibana, React, FastAPI, Pandas, Numpy, Airflow 활용"]',
    developed = '["Dedicated to the entire system construction process (data extraction, preprocessing, backend/frontend development, visualization, ETL construction)", "Built a preprocessing pipeline using Pandas and Numpy after identifying necessary items in GCP BigQuery", "Modeled operational data retention in MariaDB and search/analysis data retention in Elasticsearch and developed APIs", "Utilized FastAPI for Excel/CSV upload API, file server storage, and information extraction and preprocessing using Pandas", "Stored extracted information in MariaDB and file meta/analysis contents in Elasticsearch", "Search API linked with Elasticsearch", "Built analysis result visualization dashboard based on Elasticsearch utilizing Kibana", "Data management page based on MariaDB (inquiry, filtering, search)", "Current status/analysis page and visualization utilizing analysis data based on Elasticsearch", "Customized HandsonTable (new/modified blinking, data input dialog (MariaDB linkage), improved Undo/Redo)", "Built automated pipeline for GCP BigQuery data extraction, preprocessing, and loading into Elasticsearch and MariaDB"]',
    developed_ko = '["시스템 구축 전 과정 (데이터 추출, 전처리, 백엔드/프론트엔드 개발, 시각화, ETL 구축) 전담", "GCP BigQuery에서 시스템 필요 항목 발굴 후 Pandas, Numpy 활용 전처리 파이프라인 구축", "운영 데이터 MariaDB 저장, 검색/분석 데이터 Elasticsearch 저장 모델링 및 API 개발", "FastAPI를 활용하여 엑셀/CSV 업로드 API,  파일 서버 저장, Pandas 활용 정보 추출 및 전처리", "추출 정보 MariaDB 저장, 파일 메타/분석 내용 Elasticsearch 저장", "Elasticsearch 연동 검색 API", "Kibana 활용 Elasticsearch 기반 분석 결과 시각화 대시보드 구축", "MariaDB 기반 데이터 관리 페이지 (조회, 필터링, 검색)", "Elasticsearch 기반 분석 데이터 활용 현황/분석 페이지 및 시각화", "HandsonTable 커스터마이징 (신규/수정 깜빡임, 데이터 입력 다이얼로그 (MariaDB 연동), Undo/Redo 개선)", "GCP BigQuery 데이터 추출, 전처리, Elasticsearch 및 MariaDB 적재 자동화 파이프라인 구축"]'
WHERE slug = 'in-house-led-outsourcing-system';

-- Update In-house ILO Outsourcing Quality Monitoring System
UPDATE projects 
SET 
    process = '["Developed the entire system including frontend, backend, data processing, visualization, and ETL with a small team of 2 people", "Constructed a monitoring system to achieve the goal of monitoring quality issues occurring during the process", "Investigated distributed in-house system data and delivered information to the Data Lake team", "Utilized GCP BigQuery, React, FastAPI, Pandas, Numpy, Airflow"]',
    process_ko = '["프론트엔드, 백엔드, 데이터 처리, 시각화, ETL 등 시스템 구축 전반을 2명으로 구성된 소규모 팀으로 개발 진행", "공정 과정 중 발생하는 품질 이슈를 모니터링 목표 달성을 위한 모니터링 시스템 구축", "분산되어있는 사내 시스템 데이터를 조사 후 데이터레이크팀에게 정보 전달", "GCP BigQuery, React, FastAPI, Pandas, Numpy, Airflow 활용"]',
    developed = '["Dedicated to the entire monitoring system construction process (data extraction, preprocessing, backend/frontend development, visualization, ETL construction)", "Identified necessary items for quality monitoring in GCP BigQuery and built a preprocessing pipeline using Pandas and Numpy", "Utilized FastAPI for Excel/CSV upload API, file server storage, and information extraction and preprocessing using Pandas", "Built monitoring dashboard utilizing React and JavaScript"]',
    developed_ko = '["모니터링 시스템 구축 전 과정 (데이터 추출, 전처리, 백엔드/프론트엔드 개발, 시각화, ETL 구축) 전담", "GCP BigQuery에서 품질 모니터링에 필요 항목 발굴 Pandas, Numpy 활용 전처리 파이프라인 구축", "FastAPI를 활용하여 엑셀/CSV 업로드 API, 파일 서버 저장, Pandas 활용 정보 추출 및 전처리", "React 및 JavaScript를 활용하여 모니터링 대시보드 구축"]'
WHERE slug = 'in-house-ilo-monitoring-system';
